# ------------------ alumnos ------------------------------
inicial_lista_alumno:
    path:     /lista_alumno
    defaults: { _controller: alumnosBundle:Default:lista_alumno }

inicial_detalle_alumno:
    path:     /detalle_alumno/{id}
    defaults: { _controller: alumnosBundle:Default:detalle_alumno }

inicial_agregar_alumno:
    path:     /crear_alumno/{id_rep}
    defaults: { _controller: genericoBundle:Default:inscripcion_completa, id_rep: null  }

inicial_agregar_alumno_old:
    path:     /crear_alumno_old
    defaults: { _controller: alumnosBundle:Default:crear_alumno }

inicial_agregar_alumno_usuario:
    path:     /crear_alumno_usuario
    defaults: { _controller: alumnosBundle:Default:crear_alumno_usuario }

inicial_editar_alumno:
    path:     /editar_alumno/{id}
    defaults: { _controller: alumnosBundle:Default:editar_alumno }

inicial_borrar_alumno:
    path:     /borrar_alumno/{id}
    defaults: { _controller: alumnosBundle:Default:borrar_alumno }

inicial_pdf_alumno:
    path:     /pdf_lista_alumno
    defaults: { _controller: alumnosBundle:Default:lista_alumno_pdf }

inicial_agregar_periodo_alumno:
    path:     /crear_periodo_alumno
    defaults: { _controller: alumnosBundle:Default:crear_periodo_alumno }

inicial_lista_datos_alumno_representante:
    path:     /lista_datos_alumno_representante
    defaults: { _controller: alumnosBundle:Default:datos_alumnos_representante_lista }

inicial_datos_alumno_representante:
    path:     /datos_alumno_representante/{id}
    defaults: { _controller: alumnosBundle:Default:datos_alumnos_representante }