security:
    encoders:
        RosaMolas\usuariosBundle\Entity\PerfilUsuario:
            algorithm: bcrypt
            cost:      15

    providers:
        test_debd:
            entity:
                class: usuariosBundle:PerfilUsuario
                property: nombreUsuario
               #entity: { class: usuariosBundle:PerfilUsuario, property: nombreUsuario }
               #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
               #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            anonymous: ~
            pattern: ^/
            #http_basic: ~
            provider: test_debd

            form_login:
                login_path:  login
                check_path:  login_check
                always_use_default_target_path: true
                default_target_path: /inicio
            logout:
                path: /logout
                target: /login
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    access_control:
        #- { path: ^/, roles: [ 'ROLE_superadmin' ]  }
        #- { path: ^/inscripcion, roles: [ 'ROLE_superadmin' ]  }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/inicio, roles: [ 'ROLE_superadmin' ] }
