<?php

namespace RosaMolas\usuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasswordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordsRepository extends EntityRepository
{
}
