<?php

namespace RosaMolas\usuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContactoRepository extends EntityRepository
{
}
