generico_homepage:
    path:     /test_pdf/{id}
    defaults: { _controller: genericoBundle:Default:index }

generico_listado_alumnos_contactos:
    path:     /listado_alumnos_contactos/
    defaults: { _controller: genericoBundle:Default:listado_alumnos_contactos }

generico_constancia_inscripcion:
    path:     /constancia_inscripcion/{id}
    defaults: { _controller: genericoBundle:Default:constancia_inscripcion }

generico_constancia_estudios:
    path:     /constancia_estudios/{id}
    defaults: { _controller: genericoBundle:Default:constancia_estudios }

generico_recibo_pago:
    path:     /recibo_pago/{id}
    defaults: { _controller: genericoBundle:Default:recibo_pago }

generico_inscripcion_completa:
    path:     /inscripcion
    defaults: { _controller: genericoBundle:Default:inscripcion_completa, id_rep: null  }

generico_inscripcion_agregar_alumno:
    path:     /inscripcion_alumno/{id_rep}
    defaults: { _controller: genericoBundle:Default:agregar_alumno_inscripcion, id_rep: null  }

generico_agregar_pago:
    path:     /agregar_pago/{id}
    defaults: { _controller: genericoBundle:Default:agregar_pago }

generico_agregar_parentescos:
    path:     /crear_parentesco
    defaults: { _controller: genericoBundle:Default:crear_parentesco }

generico_editar_parentescos:
    path:     /editar_parentesco/{id}
    defaults: { _controller: genericoBundle:Default:editar_parentesco }

generico_borrar_parentescos:
    path:     /borrar_parentesco/{id}
    defaults: { _controller: genericoBundle:Default:borrar_parentesco }