generico_homepage:
    path:     /hello/{name}
    defaults: { _controller: genericoBundle:Default:index }

generico_inscripcion_completa:
    path:     /inscripcion
    defaults: { _controller: genericoBundle:Default:inscripcion_completa }

generico_inscripcion_agregar_alumno:
    path:     /inscripcion_alumno
    defaults: { _controller: genericoBundle:Default:agregar_alumno_inscripcion }

generico_agregar_pago:
    path:     /agregar_pago
    defaults: { _controller: genericoBundle:Default:agregar_pago }