generico_homepage:
    path:     /test_pdf
    defaults: { _controller: genericoBundle:Default:index }

generico_constancia_inscripcion:
    path:     /constancia_inscripcion/{id}
    defaults: { _controller: genericoBundle:Default:constancia_inscripcion }

generico_constancia_estudios:
    path:     /constancia_estudios/{id}
    defaults: { _controller: genericoBundle:Default:constancia_estudios }

generico_inscripcion_completa:
    path:     /inscripcion
    defaults: { _controller: genericoBundle:Default:inscripcion_completa }

generico_inscripcion_agregar_alumno:
    path:     /inscripcion_alumno
    defaults: { _controller: genericoBundle:Default:agregar_alumno_inscripcion }

generico_agregar_pago:
    path:     /agregar_pago/{id}
    defaults: { _controller: genericoBundle:Default:agregar_pago }