services:
#    generico.example:
#        class: RosaMolas\genericoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  funciones_genericas:
    class: RosaMolas\genericoBundle\Service\FuncionesGenericas
    arguments:
      container: "@service_container"
  RM_pdf_service:
    class: RosaMolas\genericoBundle\Service\pdfService
    arguments:
      container: "@service_container"