<?php

namespace RosaMolas\genericoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementosRepository extends EntityRepository
{
}
