<?php

namespace Test\inicialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilUsuarioRepository extends EntityRepository
{
}
